Data factory and database changes for VH Reporting SDS project
hmcts/vh-reports pull request #11
Opened 2022-12-21 10:45 UTC by fergduggan

### Change description ###

Remove dependencies on Application Insights 
Add Device information from vhvideo Heartbeat table
Update business views in vhreporting
New device table in vhreporting

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-12-21 14:49 UTC, chris-pateman requested changes

2022-12-21 14:49 UTC, chris-pateman commented on credential/vh-adf-mi-dev.json
> +}
This is not needed in here as it is added via the pipeline

2022-12-21 14:49 UTC, chris-pateman commented on credential/credential1.json
> +}
This is not needed in here as it is added via the pipeline

2022-12-21 14:49 UTC, chris-pateman commented on dataset/AsqlSource.json
> +	"properties": {
You need to remove these as they are not needed

2022-12-21 14:49 UTC, chris-pateman commented on dataset/AsqlTarget.json
> +	"properties": {
You need to remove these as they are not needed

2022-12-21 14:49 UTC, chris-pateman commented on factory/vh-datafactory-dev.json
> +}
This is not needed as it is deployed

2022-12-21 14:49 UTC, chris-pateman commented on linkedService/vhreporting-sds-kv-link.json
> +	"type": "Microsoft.DataFactory/factories/linkedservices",
You need to remove these as they are not needed

2022-12-21 14:49 UTC, chris-pateman commented on linkedService/vhreporting_blob.json
>  }
This is not needed as it is deployed

2022-12-21 14:49 UTC, chris-pateman commented on managedVirtualNetwork/default/managedPrivateEndpoint/AzureBlobStorage958.json
> +}
This is not needed as it is deployed

2022-12-21 14:49 UTC, chris-pateman commented on managedVirtualNetwork/default/managedPrivateEndpoint/vhadfendpoint.json
> +}
This is not needed as it is deployed

2022-12-21 14:49 UTC, chris-pateman commented on managedVirtualNetwork/default/managedPrivateEndpoint/vhadfsdsendpoint.json
> +}
This is not needed as it is deployed

2022-12-21 14:49 UTC, chris-pateman commented on pipeline/Child_AsqlToAsql.json
> +	"properties": {
remove as will break pipelines

2022-12-21 14:49 UTC, chris-pateman commented on pipeline/Master_PurgeData.json
> +	"properties": {
remove as will break pipelines

2022-12-21 14:49 UTC, chris-pateman commented on pipeline/Master_Staging.json
> +	"properties": {
remove as will break pipelines

2022-12-21 14:49 UTC, chris-pateman commented on publish_config.json
> +{"publishBranch":"adf_publish"}
not requried

2022-12-21 14:49 UTC, chris-pateman commented on trigger/Daily_Purge_Data.json
> +	"properties": {
remove as will break pipelines

2022-12-21 14:49 UTC, chris-pateman commented on trigger/Daily_VH_Video_Data_Load.json
> +	"properties": {
remove as will break pipelines

2022-12-22 11:10 UTC, fergduggan reviewed
Fixes look correct

2022-12-22 11:12 UTC, fergduggan commented
Reopen with fixes

2022-12-22 11:12 UTC, closed without merging